### ISSUE TITLE
Issue in index.js file.

### ISSUE THREAD

**Issue by ommiles** [learn-co-curriculum/phase-0-pac-3-what-is-a-test#1] opened 2021-03-16 23:21 UTC
I believe that the message in the assignment will not be logged in the console unless the below is commented out:

`module.exports = {name, height, message};`

**Comment by lizbur10** [comment] 2021-03-23 17:42
Hi there! I'm not able to reproduce this issue, so I'm going to go ahead and close it.

If you can provide further detail about the steps required to reproduce the issue, I'd be happy to take a second look!

As always, thanks for contributing! 💙

**Closed as completed by lizbur10** 2021-03-23 17:42 UTC
